### ISSUE TITLE
Simulator support

### ISSUE THREAD

**Issue by tksohishi** [Aralekk/simple360player_iOS#5]
It doesn't look like working on Simulator. Do you think it's possible to support this on Simulators?

**Comment by Aralekk** [comment]
It actually kind of "work" on the simulator if you do not display a video. The issue comes from the SKVideoNode texture.
If you just change this : 

videoNode.geometry?.firstMaterial?.diffuse.contents     = spriteKitScene

into

videoNode.geometry?.firstMaterial?.diffuse.contents     = UIColor.blueColor()

you'll this that it displays.
But the simulator doesn't support playing a video on a texture it seems
